### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by mcarans** [flakehell/flakehell#25]
I have made a [PR](https://github.com/flakehell/flakehell/pull/23) to make Flakehell work with Flake8 4.0.x but received no response to it. There seems to be a lack of any development activity in this repository and other PRs remain unlooked at. 

I contacted the previous maintainer from before this fork was created and he gave me who he thought was the current maintainer which matches with the last comment on the only closed issue of this fork: https://github.com/flakehell/flakehell/issues/9#issuecomment-920018318 (Sergey Gaynetdinov) I emailed Sergey, but have received no response so far. 

I want to establish if this project is being maintained or not. Please could whoever is maintainer respond and indicate if you intend to maintain this project or not.

**Comment by mcarans** [comment]
I got an email response from Sergey: "Thanks for PR, I will look into it during this week"

**Comment by mcarans** [comment]
I've sent a follow up email today as there has not been any feedback on the PR so far.

**Comment by mcarans** [comment]
I have received no response to my follow up email. @sgaynetdinov please can you indicate if you intend to maintain this project going forwards or if you seek to pass on maintenance to someone else.

**Comment by lyz-code** [comment]
thanks for the followup work @mcarans :)

**Comment by bergerx** [comment]
I previously commented on governance and maintenance being done (actually not done) single handedly here: https://github.com/flakehell/flakehell/issues/5#issuecomment-942792254

This repo seemed like a good and promising initiative. But after seeing no responses in any of the issues or PR for such long period, i strongly believe that this is an abandoned project by the owner. There is even no update in this particular issue, this delivers a quite clear signal about the owner's unwillingness to maintain (i still hope there is some other reason behind this extended unresponsiveness).

And, at this point, if there is someone with the will and energy to lead a new effort (hopefully also aiming to build a better governance and maintenance this time), I'd strongly suggest to give it a try.

**Comment by mcarans** [comment]
I have just sent another followup email to Sergey: "There are several issues and PRs with no response from you including mine and no sign of activity in the flakehell repository. Do you have the capacity to maintain flakehell? If not, would you consider passing on maintenance to someone else?"

**Comment by jarojasm95** [comment]
hey @mcarans I'd be interested in helping out setup the new flakeheaven org/repo/project if that's the direction you're leaning towards

**Comment by lyz-code** [comment]
Yeah, I can give a hand too

**Comment by mcarans** [comment]
@sgaynetdinov You have closed this issue without replying. Is it your intention to maintain flakehell?

**Comment by sgaynetdinov** [comment]
Yes, I will maintained this project.

Also I to search second maintainer for helping

**Comment by pwoolvett** [comment]
> Yes, I will maintained this project.
> 
> Also I to search second maintainer for helping

Hi @sgaynetdinov!

Together with 
@mcarans
@lyz-code
@jarojasm95 

We have been working over at [flakeheaven](https://github.com/flakeheaven/flakeheaven)

* The name change was required to publish on pypi, as requested by the original author, so we changed it everywhere
* already merged several PRs
* its being published on [pypi](https://pypi.org/project/flakeheaven/)
* docs on [read the docs](https://flakeheaven.readthedocs.io/en/latest/)

Would you like to join us? Or maybe the other way around, whichever you prefer...

@bergerx
