### ISSUE TITLE
Remove forked status of repository

### ISSUE THREAD

**Issue by uSpike** [flakehell/flakehell#9]
Hi, I started using flakehell recently and it's great.  However, the fact that this official repository is a fork removes some key benefits, like code searching.  I'm not sure what benefit there is to have this repository be a fork since the upstream is archived.  Please consider making it a standalone repository.

**Comment by djmattyg007** [comment]
You should be able to make this happen by emailing github support.

**Comment by sgaynetdinov** [comment]
Hi, I emailing Github Support, waiting the result...

**Comment by sgaynetdinov** [comment]
label (status) fork is remove
